### ISSUE TITLE
JIS0208.TXT is considered as non-free?

### ISSUE THREAD

**Issue by kmuto** [hisashim/docdiff#12]
Debian Bug#801497 claims devutil/JIS0208.TXT appears non-free.

I red copyright of this file and wondered the sentence;
> Unicode, Inc. pecifically excludes the right to re-distribute this file directly to third parties or other organizations whether for profit or not.

**Comment by hisashim** [comment]
Thank you very much for pointing this out.

Confirmed. https://github.com/hisashim/docdiff/pull/13 may fix this.
If you think this will fix the situation, I'll merge it.

This is my fault and I sincerely apologize for having overseen this for years.
I have to thank Dmitry as well.

**Comment by kmuto** [comment]
It seems OK as long as devutil/Rakefile won't be called from main build process.
In my build test, the Rakefile isn't called. So it will be OK, I believe.

FYI,
Debian policy disallows to retrieve files from network during  the build process.

**Comment by hisashim** [comment]
Thank you for the confirmation and advice. Merged #13.

// Thanks for maintaining DocDiff Debian package, as always.
